Repository GDSC-BSIOTR/Games, pull requests merged in 2022-09, with the labels that each got.

#9 Added id 5
  game.json
Labels: hacktoberfest, hacktoberfest-accepted

#29 Update game.json
  game.json
Labels: hacktoberfest-accepted

#40 Commite
  game.json
Labels: hacktoberfest-accepted

#3 Added ID 4
  game.json
Labels: hacktoberfest-accepted

#44 Update game.json
  game.json
Labels: hacktoberfest-accepted

#42 added myself at 22
  game.json
Labels: hacktoberfest-accepted

#41 Update game.json
  game.json
Labels: hacktoberfest-accepted

#38 Update game.json
  game.json
Labels: hacktoberfest

#20 Added information
  game.json
Labels: hacktoberfest-accepted

#19 added new id
  game.json
Labels: hacktoberfest, hacktoberfest-accepted

#47 Update game.json
  game.json
Labels: hacktoberfest-accepted

#17 added sports
  game.json
Labels: hacktoberfest-accepted

#13 added game
  game.json
Labels: hacktoberfest-accepted

#14 Added id 5
  game.json
Labels: hacktoberfest-accepted

#15 added info
  game.json
Labels: hacktoberfest-accepted

#12 Added id 4
  game.json
Labels: hacktoberfest-accepted

#48 Added My Game
  game.json
Labels: hacktoberfest-accepted

#51 added
  game.json
Labels: hacktoberfest-accepted

#52 Update game.json
  game.json
Labels: hacktoberfest, hacktoberfest-accepted

#53 updated id 24
  game.json
Labels: hacktoberfest-accepted

#54 Update game.json
  game.json
Labels: hacktoberfest-accepted

#55 coc
  game.json
Labels: hacktoberfest-accepted

#56 game
  game.json
Labels: hacktoberfest-accepted

#57 Update game.json
  game.json
Labels: hacktoberfest-accepted

#58 added
  game.json
Labels: hacktoberfest-accepted

#59 updated
  game.json
Labels: hacktoberfest-accepted

#60 Game
  game.json
Labels: hacktoberfest, hacktoberfest-accepted

#61 add title
  game.json
Labels: hacktoberfest-accepted

#62 commited!
  game.json
Labels: hacktoberfest, hacktoberfest-accepted

#63 Update game.json
  game.json
Labels: hacktoberfest, hacktoberfest-accepted

#64 Update
  game.json
Labels: hacktoberfest, hacktoberfest-accepted

#65 Update game.json
  game.json
Labels: hacktoberfest, hacktoberfest-accepted

#67 Update game.json
  game.json
Labels: hacktoberfest, hacktoberfest-accepted

#66 Updated
  game.json
Labels: hacktoberfest, hacktoberfest-accepted

#68 Brain out added
  game.json
Labels: hacktoberfest-accepted

#69 Update game.json
  game.json
Labels: hacktoberfest, hacktoberfest-accepted

#70 added game id
  game.json
Labels: hacktoberfest-accepted

#72 Changes done new
  game.json
Labels: hacktoberfest, hacktoberfest-accepted

#73 update
  game.json
Labels: hacktoberfest, hacktoberfest-accepted
